### ISSUE TITLE
Lost my unraid system after running step!

### ISSUE THREAD

**Issue by devliq** [jkluch/unraid-docker-swarm#1]
Please help! How can I undo this? I lost my unraid server. I have access via ssh only.

**Comment by jkluch** [comment]
Restarting the server should resolve any problems you have if you only ran up through step1.sh.  These scripts aren't entirely up to date anymore and I don't know if the process in the scripts work on the latest unraid.  Either way, you shouldn't run these scripts unless you understand what they're doing.  It might be better if you just use it as a guide and execute the commands 1 by 1.

**Comment by devliq** [comment]
I did a restart and Unraid is still installed as it boots up to the terminal prompt. But the server on port 80 is not running, all drives are unmounted and my config folder has been replaced with a config file. I am going to attempt to recover any deleted files from the USB drive. Hopefully my config folder and files are somewhere in there.

And yeah I should have tried to figure out what the script did before running it. Stupid me.

**Comment by jkluch** [comment]
I'm sorry to hear that. I realize I didn't sound very sympathetic in my initial response but I am sorry the scripts broke your unraid instance. Even with the scripts being potentially out of date I'm not sure what exactly would have caused your config folder to be replaced by a file. Maybe If you didn't have the variable.sh script downloaded or it didn't execute successfully? Unfortunately I'm actually on vacation at the moment and don't even have access to my own instance.  I hope you're able to recover.  Once I have time I'll update this project and add some warnings that these scripts were roughly put together and not as simple as just execute and you're good.

**Comment by devliq** [comment]
No worries bro, I fixed it by doing a file recovery with TestDisk. It found my config folder, which got renamed to _ONFIG, and a few other files were named as such. _DENT.CFG _O etc, I renamed the files that were all Capitalized, copied the config folder to my USB drive and all is well.

Thank you for following up. Enjoy your vacation. Be safe.
